# Generated by Django 6.0.3 on 2026-03-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("domain", models.CharField(max_length=200)),
                ("rss_url", models.URLField()),
                ("bias_rating", models.CharField(blank=True, max_length=50)),
                ("reliability_score", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
