# Generated by Django 6.0.3 on 2026-03-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="source",
            options={"ordering": ["category", "name"]},
        ),
        migrations.RemoveField(
            model_name="source",
            name="bias_rating",
        ),
        migrations.RemoveField(
            model_name="source",
            name="reliability_score",
        ),
        migrations.AddField(
            model_name="source",
            name="category",
            field=models.CharField(
                choices=[("business", "Business"), ("tech", "Tech")],
                default="business",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="source",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="source",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="rss_url",
            field=models.URLField(unique=True),
        ),
    ]
