# Generated by Django 6.0.3 on 2026-03-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="sentiment",
        ),
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[("business", "Business"), ("tech", "Tech")],
                default="business",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="article",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="article",
            name="rss_excerpt",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="article",
            name="scraped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="summarized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="summary_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="article",
            name="summary_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
