# Generated by Django 6.0.3 on 2026-03-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_remove_article_sentiment_article_author_and_more"),
        ("sources", "0002_alter_source_options_remove_source_bias_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="sentiment_label",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="article",
            name="sentiment_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["published_at"], name="articles_ar_publish_a51805_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["summary_status"], name="articles_ar_summary_8aa0e5_idx"
            ),
        ),
    ]
